kind: pipeline
type: docker
name: default

steps:
- name: Run Cypress Tests
  image: cypress/browsers:node12.18.3-chrome89-ff86
  commands:
    - cd meal-memo-ui
    - npx pnpm add -g pnpm 
    - pnpm install --quiet
    - pnpm run e2e-ci