kind: pipeline
type: docker
name: default

steps:
- name: Run Cypress Tests
  image: cypress/browsers:node16.5.0-chrome94-ff93
  commands:
    - cd meal-memo-ui
    - npm install --quiet
    - ./node_modules/.bin/cypress run --headless --browser chrome --spec 'cypress/integration/**/*spec*.ts'