kind: pipeline
type: docker
name: default

steps:
cypress_run:
    image: cypress/browsers:node16.5.0-chrome94-ff93
    commands:
      - npm install
      - ./node_modules/.bin/cypress run --headless --browser chrome --spec 'cypress/integration/UI/**/*spec*.ts'